### ISSUE TITLE
Removing an active action adapter would result in a KeyError on form submit. 

### ISSUE THREAD

**Issue by jeb6** [smcmahon/Products.PloneFormGen#154]
This error is back in PloneFormGen 1.7.12 using Plone 4.3.3  It was in the alpha version earlier.

Joe Bigler

**Comment by jeb6** [comment]
Here is the traceback:
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 91, in __call__
  Module Products.CMFFormController.BaseControllerPageTemplate, line 27, in _call
KeyError: 'form.submitted'

This was caused by removing the mailer adapter.  I tried adding it back, but the problem is still there.  Is there a way to fix this?

**Comment by jeb6** [comment]
I tried creating a new Plone site with only PloneFormGen added on the same server and a different server. Same versions of software. The problem did not duplicate in either case.

**Comment by ida** [comment]
@jeb6: If I get you right, everything works well in a fresh setup? I'm afraid we can't help you much further then, because you need to figure out which further done customizations or additional addons are the cause for the error. If you could provide infos about a setup, where the error is reproducable (via a buildout-config, e.g.), there'd be a chance for others to recreate the error and debug it. Regards, Ida

**Comment by jeb6** [comment]
I created a fresh Plone site with the same software on another server.  The problem appears to be only with my site so I am closing this report.
